<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VTJS6APB" failures="1" tests="12" name="Testrunner2" time="2.839" errors="0" timestamp="2020-06-03T17:46:43 IST">
  <testcase classname="testNG2.ReportingTest" name="login" time="0.017"/>
  <testcase classname="testNG2.ReportingTest" name="logout" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [test1] but found [test]">
      <![CDATA[java.lang.AssertionError: expected [test1] but found [test]
at testNG2.ReportingTest.logout(ReportingTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- logout -->
  <testcase classname="testNG2.PayementReturn" name="paymentreturnedByBank" time="0.011"/>
  <testcase classname="testNG2.SingUpTest" name="singupviaEmail" time="0.006"/>
  <testcase classname="testNG2.SingUpTest" name="singupviaFacebook" time="0.004"/>
  <testcase classname="testNG2.SingUpTest" name="singupviaTwitter" time="0.001"/>
  <testcase classname="testNG2.TestNGDataProviders" name="registerUser" time="0.002"/>
  <testcase classname="testNG2.TestNGDataProviders" name="registerUser" time="0.001"/>
  <testcase classname="testNG2.TestNGDataProviders" name="registerUser" time="0.001"/>
  <testcase classname="testNG2.TestNGDataProviders" name="Login" time="0.001"/>
  <testcase classname="testNG2.TestNGDataProviders" name="Login" time="0.002"/>
  <testcase classname="testNG2.TestNGDataProviders" name="Login" time="0.002"/>
</testsuite> <!-- Testrunner2 -->
